// Roteiros de consulta: não navegam, não alteram filtros nem gravam dados.
const step = (target, title, text, permission = null) => ({ target, title, text, permission });
const intro = (title, text) => step('.page-head, .editor-head, .student-course-head', title, text);
const metrics = (text) => step('.metric-grid, .people-summary, .notification-summary', 'Entenda os números', text);
const create = (dialog, title, text, permission) => ({ ...step(`[data-dialog="${dialog}"]`, title, text, permission), action: { dialog, label: 'Abrir formulário' } });
const rows = (title, text) => step('.people-list, .company-grid, .list-table, .card', title, text);
const tabs = (target, text) => step(target, 'Abas desta área', text);
const guide = (title, ...steps) => ({ title, steps });
const vacancyFilters = step('.operations-toolbar', 'Localize o registro', 'Busque por nome, e-mail, vaga ou empresa. Combine situação e empresa. Limpar remove os filtros; não exclui cadastros.');
const documentFilters = step('.filter-bar', 'Busque e classifique', 'Pesquise pelo documento, jovem ou empresa e refine pela categoria. Limpar filtros mostra novamente os registros disponíveis.');
const financeTabs = tabs('[aria-label="Áreas do financeiro"]', 'Contas a receber controla cobranças às empresas; Contas a pagar controla despesas; Calendário reúne os vencimentos. Feche o guia para trocar de aba e clique novamente em Como usar.');

export const pageGuides = {
  overview: guide('Visão geral',
    intro('Comece pelas prioridades', 'Esta página resume a operação disponível ao seu departamento. O guia explica apenas esta tela; abra outra aba e use Como usar para ver o roteiro dela.'),
    metrics('Os cartões mostram registros reais da operação. Zero significa que não há registros naquele recorte, não que você precisa criar exemplos.'),
    step('.attention-list, .attention-clear', 'Precisa da sua atenção', 'Veja atrasos, prazos e alertas. Depois de fechar o guia, abra o item para tratar a pendência na área responsável. A ausência de alertas é uma situação normal.'),
    create('task', 'Registre uma providência', 'Nova tarefa abre um cadastro com título, responsável, prazo, prioridade e checklist. O responsável receberá a notificação quando você salvar.', 'operations.manage'),
    step('.checklist-item', 'Próximas ações', 'Estes atalhos levam às rotinas relacionadas. Consulte os cadastros existentes antes de criar qualquer novo registro.')),
  pipelines: guide('Central de Esteiras',
    intro('Processos organizados por etapa', 'Cada cartão representa um processo. A esteira escolhida define quais etapas e processos aparecem no quadro.'),
    step('[data-pipeline-select]', 'Escolha a esteira', 'Selecione a rotina que deseja acompanhar. Confira a descrição e os contadores de processos exibidos, atrasados e sem responsável.'),
    create('pipeline-item', 'Crie um processo', 'Informe título, descrição, etapa, responsável, prioridade e prazo. Vincule empresa ou jovem quando fizer sentido. Primeiro é necessário haver uma esteira ativa.', 'operations.manage'),
    step('.filter-bar', 'Busque e ordene', 'Combine busca, prioridade, responsável e empresa. Ordene por movimentação recente, antiguidade, prazo ou prioridade. Os filtros só mudam a visualização.'),
    step('.kanban-board', 'Leia o quadro', 'As colunas são as etapas. Cada cartão mostra vínculos, prazo e responsável. O destaque de atraso pede revisão do prazo ou da providência.'),
    step('[data-edit-pipeline-item]', 'Atualize ou mova', 'O lápis abre os detalhes e o histórico. Arrastar um cartão muda sua etapa e grava a movimentação; no celular use Mover para. Faça isso apenas após a etapa realmente avançar.', 'operations.manage')),
  tasks: guide('Tarefas e Pendências',
    intro('Organize o trabalho', 'Tarefas registram uma providência, quem deve realizá-la e o prazo. Use o checklist para dividir o trabalho em partes.'),
    step('.task-filter-tabs', 'Escolha o recorte', 'Minhas mostra pendências atribuídas a você. Hoje, Atrasadas, Próximas e Concluídas ajudam a organizar a rotina. Trocar de recorte não altera as tarefas.'),
    create('task', 'Crie a primeira tarefa', 'Defina um título objetivo, resultado esperado, prioridade, prazo e responsável. Você pode vincular empresa, jovem e processo, além de escrever um item do checklist por linha.', 'operations.manage'),
    step('.task-card', 'Leia os detalhes', 'Confira situação, categoria, vínculos, responsável e vencimento. O lápis permite ajustar o cadastro sem criar uma tarefa duplicada.'),
    step('.task-checklist', 'Marque o checklist', 'Marque apenas o que já foi realizado. Cada marcação é uma alteração real; percorrer este guia não marca itens.', 'operations.manage'),
    step('[data-task-status]', 'Conclua ou reabra', 'Concluir encerra a tarefa. Reabrir devolve uma tarefa concluída para acompanhamento. Confirme a execução antes de encerrar.', 'operations.manage')),
  notifications: guide('Notificações',
    intro('Avisos dirigidos a você', 'Esta tela reúne atribuições, prazos e alertas do seu trabalho. Ela não mostra a caixa de notificações de outras pessoas.'),
    metrics('Não lidas indica avisos ainda não vistos; Em aberto mostra avisos ativos; Resolvidas reúne os que foram encerrados.'),
    step('[data-notification-filter]', 'Filtre os avisos', 'Escolha Em aberto, Não lidas, Resolvidas ou Todas. Ler um aviso não conclui a tarefa ou processo que o originou.'),
    step('.notification-row', 'Abra a origem', 'Confira título, mensagem e prazo. Abrir leva à área relacionada, quando seu perfil possui acesso.'),
    step('.notification-actions, [data-read-all-notifications]', 'Ler não é resolver', 'Marcar como lida organiza sua caixa. Dispensar encerra o aviso, mas não executa a providência. Trate a pendência no cadastro de origem.')),
  'automations:overview': guide('Automações · Visão geral',
    intro('Acompanhe as rotinas automáticas', 'O portal identifica pendências e prazos e registra as execuções. Aprovações e decisões importantes continuam com a equipe.'),
    step('[data-automation-tab]', 'Áreas de automação', 'As subabas exibidas dependem das suas permissões. E-mails, Documentos, Bradesco e Histórico têm guias próprios.'),
    metrics('Confira alertas ativos, urgências, tarefas geradas e a última atualização. Consulte o histórico quando houver falhas.'),
    step('[data-run-automations]', 'Atualizar agora', 'Este botão executa a rotina e pode gerar ou encerrar alertas e tarefas derivados. O tutorial não executa a rotina.', 'operations.manage'),
    step('.automation-principles', 'O que permanece manual', 'Revisão de documentos, envio externo, contratação, desligamento e decisões financeiras exigem ação humana.'),
    rows('Providências identificadas', 'Leia a mensagem de cada alerta e abra a área correspondente para resolver a causa.')),
  'automations:emails': guide('Automações · E-mails',
    intro('Prepare e confira antes de enviar', 'Rascunho, aprovação e envio são situações diferentes. Ter um rascunho no portal não significa que alguém recebeu o e-mail.'),
    create('email-draft', 'Preparar e-mail', 'Escolha o modelo e confira destinatário, assunto, mensagem e anexo. O formulário tem ajuda campo a campo.', 'finance.manage'),
    rows('Acompanhe a situação', 'Confira data, destinatário e status. Se houver falha, leia o motivo antes de tentar de novo para evitar envios desnecessários.'),
    step('[data-edit-email-draft]', 'Conferir o conteúdo', 'Abra o rascunho e confira dados pessoais, empresa, valores e documentos antes da comunicação externa.', 'finance.manage'),
    step('[data-send-email]', 'Enviar é uma ação real', 'Enviar dispara a comunicação para o destinatário configurado. O guia não clica nesse botão nem confirma envios por você.', 'finance.manage')),
  'automations:documents': guide('Automações · Documentos',
    intro('PDFs com revisão', 'Os documentos gerados têm protocolo e versão e começam como rascunho. Revise antes de usar fora do portal.'),
    create('document-generation', 'Gerar documento', 'Escolha o modelo e vincule o cadastro real. Confira as informações antes da geração do PDF.', 'documents.manage'),
    rows('Versões e situação', 'A lista mostra título, versão, data e revisão. Um documento aguardando revisão ainda não está aprovado.'),
    step('[data-download-document]', 'Baixe para conferir', 'Use Baixar para revisar o PDF e verificar identificação, datas e conteúdo.'),
    step('[data-review-generation]', 'Aprovar ou rejeitar', 'Somente aprove após a conferência. O guia explica os controles, mas não decide a revisão.', 'documents.manage')),
  'automations:banking': guide('Automações · Bradesco',
    intro('Preparação bancária', 'Esta área organiza a futura integração. O cadastro atual não emite boletos, envia pagamentos nem faz conciliação automática.'),
    step('.banking-readiness', 'Confira os requisitos', 'A ativação depende da documentação, convênio, carteira, credenciais e homologação com o banco. Não confunda cadastro com conexão ativa.'),
    create('banking-integration', 'Cadastrar dados confirmados', 'Informe somente os dados operacionais confirmados pelo banco. Nunca cole senha bancária, chave privada ou segredo de API nos campos de observação.', 'finance.manage'),
    rows('Acompanhe a configuração', 'Consulte modo, convênio, leiaute e situação. Alterar o status deste cadastro não libera uma integração por si só.')),
  'automations:history': guide('Automações · Histórico',
    intro('Histórico de execuções', 'Use esta aba para saber quando a rotina foi executada e qual foi o resultado.'),
    rows('Origem e horário', 'Cada linha distingue atualização manual, agendada ou do sistema e informa quando começou.'),
    rows('Leia os totais', 'Alertas, notificações e tarefas são resultados da execução. Não representam pontuação ou produtividade individual.'),
    rows('Quando houver falha', 'Registre o horário e a mensagem mostrada para solicitar suporte. Não compartilhe senhas ou dados privados em capturas.')),
  indicators: guide('Indicadores e relatórios',
    intro('Leia o recorte permitido', 'Os relatórios usam dados reais e respeitam o departamento. A visão individual de carga não é um ranking de funcionários.'),
    step('#indicator-filter-form', 'Período e área', 'Escolha início, fim e área e clique Atualizar relatório. O intervalo é limitado pelo sistema. O período de um relatório não transforma todo indicador em uma série histórica.'),
    step('.indicator-metrics', 'Indicadores', 'Leia o nome e o formato de cada indicador. Cartões com destino disponível abrem a área responsável; metas aparecem quando cadastradas.'),
    step('.indicator-list', 'Gargalos e pendências', 'Use os alertas para identificar o que precisa de providência. Resolva a causa no módulo correspondente, não no relatório.'),
    step('.stage-report-list', 'Tempo nas etapas', 'Confira quantidade e tempo médio dos processos por etapa. Isso ajuda a localizar etapas paradas e não classifica funcionários.'),
    step('#work-log-form', 'Registrar carga operacional', 'Escolha cronômetro ou lançamento manual em minutos. Informe a atividade e vincule tarefa ou processo se desejar. Salvar inicia ou registra tempo real; o guia não faz isso.'),
    step('.active-work-log, .recent-work-logs', 'Pausar e concluir', 'Quando houver cronômetro em andamento, pause em interrupções e conclua ao terminar. Confira os lançamentos recentes.'),
    step('#indicator-target-form', 'Metas institucionais', 'Somente a Direção define indicador, área, período, comparação e valor. Metas são opcionais e não são preenchidas automaticamente.', 'targets.manage'),
    step('[data-export-indicators]', 'Exportar CSV', 'A exportação é registrada na auditoria e respeita o acesso. Confira o recorte e compartilhe o arquivo somente com pessoas autorizadas.', 'reports.export')),
  companies: guide('Empresas parceiras',
    intro('Cadastro único de empresas', 'Mantenha dados institucionais e de contato atualizados. Jovens, representantes e processos usam estes vínculos.'),
    create('company', 'Cadastrar empresa', 'Confira se a empresa já existe. Informe identificação, CNPJ quando disponível, contatos e endereço. O formulário orienta cada campo.', 'companies.manage'),
    step('.company-card', 'Leia o cartão', 'Confira situação, contatos, endereço e quantidades vinculadas. Use estes dados para identificar a organização correta.'),
    step('[data-edit-company]', 'Editar dados', 'Abra o lápis para corrigir o cadastro existente, sem duplicar a empresa.', 'companies.manage'),
    step('[data-toggle-company]', 'Ativar ou inativar', 'Inativar preserva o histórico e muda a disponibilidade da empresa. Confira os vínculos antes de alterar.', 'companies.manage'),
    step('[data-delete-company]', 'Cuidado ao excluir', 'Excluir não é o mesmo que inativar e pode ser impedido por vínculos. Leia a confirmação e prefira preservar o histórico quando necessário.', 'companies.manage')),
  apprentices: guide('Jovens / Aprendizes',
    intro('Consulte o cadastro central', 'Use esta lista para localizar jovens, conferir empresas e acompanhar dados acadêmicos disponíveis ao seu perfil.'),
    metrics('Veja a quantidade de jovens e os vínculos apresentados. Ausência de matrícula não significa ausência de cadastro.'),
    create('invite', 'Cadastrar acesso do jovem', 'Confira se a pessoa já existe e use um e-mail correto. Salvar o convite é uma ação real, não um teste.', 'people.manage'),
    step('.apprentice-row, .person-row', 'Vínculos e progresso', 'Confira empresa, situação, matrículas, aulas e atividades antes de orientar o jovem.'),
    step('[data-person-history]', 'Histórico do jovem', 'O histórico reúne vínculos e registros permitidos ao departamento. Evite copiar informações pessoais para locais públicos.', 'apprentice.history.read'),
    step('[data-edit-person]', 'Corrigir cadastro', 'Faça ajustes no registro existente. Não crie outro acesso para corrigir um nome ou vínculo.', 'people.manage')),
  'vacancies:overview': guide('Gestão de vagas · Resumo',
    intro('Da oportunidade à admissão', 'O fluxo usa empresa, vaga, candidato e seleção. Cada um tem um cadastro próprio, conectado aos demais.'),
    metrics('Empresas ativas, posições disponíveis, candidatos e seleções ajudam a entender a demanda atual.'),
    step('[data-vacancy-tab]', 'Escolha a subaba', 'Vagas detalha oportunidades; Candidatos guarda perfis; Seleções acompanha cada encaminhamento. Cada subaba tem seu Como usar.'),
    create('vacancy', 'Abrir uma vaga', 'Cadastre empresa, título, quantidade, requisitos e prazo usando a demanda real da empresa.', 'vacancies.manage'),
    create('candidate', 'Cadastrar candidato', 'Confira se o candidato já existe antes de informar contatos e currículo. Candidato ainda não é um acesso de jovem.', 'vacancies.manage'),
    create('application', 'Iniciar seleção', 'Vincule um candidato existente a uma vaga e acompanhe os avanços. A admissão começa somente após aprovação.', 'vacancies.manage')),
  'vacancies:vacancies': guide('Gestão de vagas · Vagas',
    intro('Oportunidades das empresas', 'Esta aba lista as demandas registradas. A quantidade disponível considera as posições preenchidas.'),
    vacancyFilters,
    create('vacancy', 'Abrir vaga', 'Escolha a empresa, descreva função e requisitos e informe quantidade, local, prazo e situação.', 'vacancies.manage'),
    rows('Preenchimento e prazo', 'Cada vaga mostra empresa, posições preenchidas e restantes. Confira o prazo e o status antes de encaminhar alguém.'),
    step('[data-edit-vacancy]', 'Manter a vaga atualizada', 'Altere o cadastro quando a empresa mudar requisitos, quantidade ou situação. Evite duplicar uma demanda já aberta.', 'vacancies.manage')),
  'vacancies:candidates': guide('Gestão de vagas · Candidatos',
    intro('Banco de candidatos', 'Um candidato pode participar de seleções. O cadastro de recrutamento não concede automaticamente acesso ao portal.'),
    vacancyFilters,
    create('candidate', 'Cadastrar candidato', 'Informe identificação e contato, situação e demais dados disponíveis. Revise o perfil antes de incluir documentos.', 'vacancies.manage'),
    rows('Seleções e arquivos', 'A lista mostra contatos, quantidade de seleções e arquivos. Abra o cadastro para conferir os detalhes.'),
    step('[data-edit-candidate]', 'Abrir cadastro', 'Atualize informações e documentos no registro existente para manter o histórico reunido.', 'vacancies.manage'),
    step('[data-archive-candidate]', 'Arquivar ou reativar', 'Arquivar retira o candidato do acompanhamento ativo sem recriar o cadastro. Reative quando for necessário retomar.', 'vacancies.manage')),
  'vacancies:applications': guide('Gestão de vagas · Seleções',
    intro('Acompanhe cada encaminhamento', 'Seleção liga uma vaga a um candidato e registra a etapa atual, entrevistas e retorno da empresa.'),
    vacancyFilters,
    create('application', 'Iniciar seleção', 'Escolha vaga e candidato já cadastrados. Evite repetir o mesmo encaminhamento.', 'vacancies.manage'),
    rows('Leia a etapa', 'Confira candidato, vaga, empresa e entrevista. A situação deve refletir o andamento real.'),
    step('[data-edit-application]', 'Atualizar avanço', 'Registre triagem, entrevistas, encaminhamento, retorno e resultado no mesmo processo.', 'vacancies.manage'),
    step('[data-convert-candidate]', 'Depois da aprovação', 'Iniciar admissão aparece para seleção aprovada. A conversão cria ou vincula o jovem e inicia o fluxo administrativo; exige conferência antes de confirmar.', 'vacancies.manage')),
  partnerships: guide('Parcerias e jovens',
    intro('Contratos de parceria', 'Acompanhe o acordo institucional com cada empresa. Ele é diferente do contrato individual do jovem.'),
    metrics('Os totais resumem parcerias e vínculos existentes, sem criar acordos automaticamente.'),
    create('partnership', 'Cadastrar parceria', 'Escolha a empresa, informe referência, datas, situação e condições confirmadas no contrato.', 'vacancies.manage'),
    rows('Consulte vigência e vínculos', 'Confira empresa, período e situação da parceria para acompanhar a relação institucional.'),
    step('[data-edit-partnership]', 'Atualize o acordo', 'Registre alterações no acordo correto e preserve referências que permitam localizar o documento.', 'vacancies.manage')),
  admissions: guide('Admissões',
    intro('Da aprovação ao início', 'A admissão reúne jovem, empresa, data prevista e checklist. Confirme os cadastros antes de abrir o processo.'),
    metrics('Confira quantas admissões estão em andamento e quais precisam de documentos ou providências.'),
    create('admission', 'Abrir admissão', 'Vincule jovem e empresa. Ao salvar, o portal cria checklist padrão, acompanhamento e envio à contabilidade; não use pessoas fictícias para experimentar.', 'personnel.manage'),
    step('.workflow-record', 'Etapas e documentos', 'O registro mostra o estágio do processo e o andamento do checklist. A etapa deve corresponder à situação real.'),
    step('[data-edit-admission]', 'Conferir checklist', 'Abra a admissão para marcar itens realizados, acrescentar pendências e atualizar previsão e observações. Acrescentar itens preserva os anteriores.', 'personnel.manage')),
  contracts: guide('Contratos dos jovens',
    intro('Vigência e vínculo', 'Esta área registra o contrato individual do jovem com a empresa. O cadastro não substitui o documento assinado.'),
    metrics('Leia contratos vigentes e vencimentos apresentados para planejar as providências.'),
    create('contract', 'Cadastrar contrato', 'Vincule jovem e empresa; confira início, término, função, jornada, salário e situação antes de salvar.', 'contracts.manage'),
    rows('Acompanhe vencimentos', 'Confira datas e status. O portal usa marcos de 90, 60, 30, 15 e 7 dias para o acompanhamento da vigência.'),
    step('[data-edit-contract]', 'Alterar com conferência', 'Atualize o contrato existente quando houver uma mudança confirmada. Registrar o término não executa sozinho um desligamento.', 'contracts.manage')),
  leaves: guide('Férias e afastamentos',
    intro('Registre o período', 'Use a área para acompanhar férias, afastamentos médicos e outras ausências, com previsão de retorno.'),
    metrics('Os contadores ajudam a localizar períodos planejados ou em andamento.'),
    create('leave', 'Novo registro', 'Escolha jovem, empresa e contrato quando aplicável. Defina tipo, início, término previsto e situação.', 'personnel.manage'),
    rows('Confira as datas', 'Diferencie previsão de término e retorno efetivo. Vincule ao contrato correspondente ao período.'),
    step('[data-edit-leave]', 'Registrar o retorno', 'Atualize a situação e a data efetiva quando houver confirmação. Evite colocar detalhes médicos desnecessários nas observações.', 'personnel.manage')),
  terminations: guide('Desligamentos',
    intro('Acompanhe até o encerramento', 'Reúna exame, documentos, contabilidade, rescisão e entrega no mesmo processo. Abrir o registro não realiza todos esses passos.'),
    metrics('Os totais indicam processos abertos e providências que precisam de acompanhamento.'),
    create('termination', 'Abrir desligamento', 'Confira jovem, empresa, data, motivo e etapa. O cadastro cria o checklist padrão para acompanhamento.', 'personnel.manage'),
    step('.workflow-record', 'Leia o andamento', 'Acompanhe etapa e checklist. Registre conclusão de cada providência apenas depois de conferi-la.'),
    step('[data-edit-termination]', 'Completar e documentar', 'Atualize checklist, valor e data de pagamento quando confirmados. Salvar esses dados não transfere dinheiro nem envia obrigações externas.', 'personnel.manage')),
  personnel: guide('Departamento Pessoal',
    intro('Painel do ciclo do jovem', 'Este painel conecta as rotinas administrativas. Use os atalhos para abrir o módulo que executa cada procedimento.'),
    metrics('Confira admissões abertas, contratos vigentes, férias e afastamentos e documentos pendentes.'),
    step('.administrative-hub-grid', 'Abra o módulo certo', 'Os cartões levam às áreas do DP. Depois de abrir uma, clique Como usar para aprender os controles daquela área.'),
    rows('Pendências administrativas', 'Leia os itens que exigem atenção e trate a origem indicada. O painel não resolve pendências apenas por serem visualizadas.')),
  'finance:receivable': guide('Financeiro · Contas a receber',
    intro('Controle o que a CAFCM tem a receber', 'Registre cobranças às empresas por competência e vencimento. É um controle manual; cadastrar não emite NF ou boleto no banco.'),
    financeTabs,
    metrics('A receber soma valores abertos, Vencido mostra abertos após o prazo, Recebido reúne pagamentos registrados e Cobranças conta os registros.'),
    create('financial-charge', 'Criar primeira cobrança', 'Escolha empresa, competência, descrição, valor e vencimento. Depois registre referências da NF, boleto, envio e recebimento.', 'finance.manage'),
    step('.filter-bar', 'Buscar cobranças', 'Pesquise empresa, descrição, NF ou boleto e refine por situação e empresa. Limpar filtros não altera valores.'),
    rows('Leia o vencimento', 'Cada linha mostra empresa, competência, vencimento, valor e situação. Vencido — atualizar sinaliza atraso sem registrar recebimento.'),
    step('[data-edit-financial-charge]', 'Atualize o ciclo', 'Use Alterar para registrar NF emitida, boleto, envio, cobrança e pagamento. Informe recebimento apenas após confirmação; o registro não movimenta a conta bancária.', 'finance.manage')),
  'finance:payable': guide('Financeiro · Contas a pagar',
    intro('Registre o que a CAFCM tem a pagar', 'Esta aba controla despesas e fornecedores. Ela é separada das cobranças que as empresas devem à instituição.'),
    financeTabs,
    metrics('A pagar reúne contas abertas; Vencido são abertas após a data; Pago mostra valores pagos registrados; Contas indica a quantidade cadastrada.'),
    create('payable', 'Criar conta a pagar', 'Informe fornecedor, categoria, descrição, competência, valor e vencimento. A ajuda do formulário explica datas, lembretes, responsável e comprovantes.', 'finance.manage'),
    step('.filter-bar', 'Busque a despesa', 'Pesquise fornecedor, descrição ou referência e filtre pela situação. Verifique os cadastros existentes para não duplicar uma conta.'),
    rows('Situação e vencimento', 'Aguardando aprovação, Aprovada, Programada, Paga e Cancelada descrevem o controle interno. Programada não agenda pagamento no banco.'),
    step('[data-edit-payable]', 'Lembretes e pagamento', 'Em Alterar, confira antecedência dos avisos, responsável e data prevista. Marque Paga e vincule o comprovante somente após o pagamento real.', 'finance.manage'),
    rows('O que não é automático', 'Nenhum pagamento é enviado ao banco nesta etapa. Bradesco (manual) identifica o meio informado; lembretes internos dependem da rotina de alertas.')),
  'finance:calendar': guide('Financeiro · Calendário',
    intro('Veja os vencimentos no calendário', 'A agenda mensal reúne contas a receber e a pagar já cadastradas. Não é uma agenda de transferências bancárias.'),
    financeTabs,
    step('.calendar-controls', 'Troque o mês', 'Use mês anterior ou seguinte e Hoje para voltar ao mês atual. Navegar pela agenda não altera nenhum vencimento.'),
    step('.finance-calendar > .muted-note', 'Diferencie entradas e saídas', 'A receber e A pagar possuem identificação própria. Leia o texto do evento além da cor.'),
    step('.calendar-days', 'Consulte o dia', 'Os eventos são organizados pelo vencimento. Confira descrição e valor; dias vazios não têm contas exibidas naquele recorte.'),
    step('.calendar-event', 'Abra um lançamento', 'Com permissão de alteração, clique no evento para conferir o cadastro. Para criar uma conta, vá à aba A pagar ou A receber. O guia não muda de aba por você.')),
  'documents:files': guide('Documentos · Arquivos',
    intro('Arquivo digital privado', 'Guarde documentos vinculados a jovem, empresa ou processo. Acesso e alterações seguem as permissões do departamento.'),
    metrics('Confira ativos, pendências, pendências vencidas e documentos próximos da validade.'),
    documentFilters,
    create('document', 'Enviar documento', 'Escolha arquivo, título, categoria, vínculo e validade. Se atender uma pendência existente, selecione-a no cadastro.', 'documents.manage'),
    step('[data-download-document]', 'Baixar para consulta', 'Baixe o documento autorizado e compartilhe somente com quem precisa daquela informação.'),
    step('[data-edit-document]', 'Editar identificação', 'Ajuste os dados do arquivo existente para manter a classificação e validade corretas.', 'documents.manage'),
    step('[data-archive-document]', 'Arquivar', 'Arquivar retira da lista ativa e preserva o registro para consulta em Arquivados. Não é exclusão definitiva.', 'documents.manage')),
  'documents:requirements': guide('Documentos · Pendências',
    intro('Controle o que falta', 'Pendência é a exigência de um documento. Ela pode existir antes de qualquer arquivo ser enviado.'),
    documentFilters,
    create('document-requirement', 'Nova pendência', 'Defina título, categoria, vínculo e prazo. Registre o que realmente precisa ser recebido ou conferido.', 'documents.manage'),
    rows('Situação da pendência', 'Pendente, Recebido, Conferido e Dispensado são etapas diferentes. Receber um arquivo não significa conferência concluída.'),
    step('[data-edit-document-requirement]', 'Vincular e conferir', 'Abra Alterar para vincular o documento recebido e atualizar a situação após revisão.', 'documents.manage'),
    create('document', 'Atender com um arquivo', 'No envio de documento, selecione Pendência atendida para conectar o arquivo à exigência existente.', 'documents.manage')),
  'documents:archived': guide('Documentos · Arquivados',
    intro('Consulte o arquivo preservado', 'Aqui ficam documentos retirados da lista ativa. Não é uma lixeira de exclusão definitiva.'),
    documentFilters,
    rows('Identifique o documento', 'Confira título, vínculo, categoria e validade antes de decidir reativar.'),
    step('[data-archive-document]', 'Restaurar', 'Restaurar devolve o documento à lista de Arquivos. Depois disso, consulte ou altere pela aba ativa.', 'documents.manage')),
  accounting: guide('Contabilidade',
    intro('Controle os encaminhamentos', 'Registre o assunto, envio, retorno e conferência. Cadastrar um encaminhamento não transmite eSocial nem envia e-mail automaticamente.'),
    metrics('Veja o volume de pendências e o andamento dos encaminhamentos cadastrados.'),
    create('accounting', 'Novo envio', 'Informe assunto, tipo, competência, prazo, responsável e vínculos. Use a referência externa para protocolo e vincule o documento quando existir.', 'finance.manage'),
    rows('Leia as etapas', 'Pendente, preparação, enviado, aguardando retorno, recebido, conferido e concluído permitem acompanhar o serviço.'),
    step('[data-edit-accounting]', 'Registrar retorno', 'Atualize a etapa conforme cada providência for confirmada. Recebido e Conferido representam momentos diferentes.', 'finance.manage')),
  procedures: guide('Procedimentos',
    intro('Encontre a rotina administrativa', 'Esta área reúne atalhos e pendências dos processos, sem criar uma segunda cópia de cada cadastro.'),
    metrics('Confira processos abertos, atrasados, tarefas abertas e itens sem responsável.'),
    step('.administrative-hub-grid', 'Escolha uma esteira', 'Cada cartão abre a esteira correspondente. O guia da esteira explica criação, filtros e movimentação.'),
    step('.page-actions', 'Tarefas e esteiras', 'Use Ver tarefas para providências pontuais ou Abrir esteiras para o fluxo completo.'),
    rows('Gargalos de rotina', 'Localize atrasos e falta de responsáveis, depois abra o registro de origem para corrigir.')),
  people: guide('Pessoas e Convites',
    intro('Contas e acessos', 'Esta área gerencia convites e perfis. Revise nome, e-mail, tipo de acesso e empresa antes de convidar.'),
    metrics('Os resumos distinguem acessos ativos, pendentes e situações de convite.'),
    create('invite', 'Enviar convite', 'Convide jovem ou representante da empresa. Somente a Direção administra contas internas da equipe. Confirmar o formulário pode enviar e-mail real.', 'people.manage'),
    step('[data-edit-person]', 'Editar perfil', 'Ajuste o registro existente e confira o vínculo com a empresa. Contas da equipe seguem a restrição da Direção.', 'people.manage'),
    step('[data-resend-access]', 'Recuperar acesso', 'Reenvie convite ou recuperação pelo controle disponível. Nunca peça a senha da pessoa para ajudá-la.', 'people.manage'),
    step('[data-set-person-active]', 'Arquivar ou restaurar acesso', 'Leia a confirmação antes de excluir e arquivar um acesso ou restaurá-lo. A alteração pode afetar a entrada da pessoa no portal.', 'people.manage'),
    step('[data-download-people-template]', 'Importar com o modelo', 'Baixe o modelo, preencha dados reais e revise antes de importar. A importação pode criar ou atualizar acessos e enviar convites.', 'people.manage'),
    create('people-import', 'Conferir importação', 'Leia o formato e as opções do formulário. Verifique os resultados depois de processar, inclusive as linhas com falha.', 'people.manage'),
    step('[data-export-people]', 'Exportar com cuidado', 'A exportação contém dados pessoais. Mantenha o arquivo em local protegido e compartilhe somente com pessoas autorizadas.', 'people.manage')),
  audit: guide('Auditoria',
    intro('Histórico de ações', 'A auditoria registra ações relevantes. Ela é uma consulta de histórico, não um editor de registros.'),
    metrics('Os cartões resumem as ações e pessoas disponíveis no recorte carregado.'),
    step('.audit-row, .audit-list', 'Quem, o quê e quando', 'Cada linha informa ação, responsável, relação com outra pessoa quando existente e data e hora.'),
    step('[data-clear-audit-filter]', 'Filtro por pessoa', 'Quando o histórico foi aberto a partir de uma pessoa, remova o filtro para voltar à lista geral permitida.'),
    rows('Investigar com contexto', 'Compare a ação ao registro de origem. Não compartilhe histórico com dados pessoais fora das pessoas autorizadas.')),
  courses: guide('Cursos',
    intro('Organize a formação', 'A estrutura é Curso → Aula → Linhas de aprendizagem → Atividade. Criar curso é diferente de matricular um jovem.'),
    create('course', 'Novo curso', 'Informe título, categoria, descrição, objetivos e carga horária. O curso começa em rascunho até a publicação.', 'academic.manage'),
    step('.course-card', 'Leia o resumo', 'Cada cartão apresenta situação, carga horária e quantidade de aulas e atividades.'),
    step('[data-open-course]', 'Abrir estrutura', 'Abra um curso para organizar aulas e atividades. O editor tem seu próprio Como usar.'),
    step('.course-grid', 'Publicação e matrícula', 'Revise a estrutura antes de publicar. Use Matrículas para vincular jovens ao curso; apenas criar o conteúdo não cria matrículas.')),
  'course-editor': guide('Editor do curso',
    intro('Estruture este curso', 'Confira a identificação e organização do curso antes de publicá-lo para os jovens.'),
    step('[data-edit-course]', 'Dados do curso', 'Edite título, descrição, objetivos, categoria e carga horária.', 'academic.manage'),
    create('lesson', 'Criar aula', 'Cadastre título e posição. Depois abra a aula para inserir linhas de aprendizagem.', 'academic.manage'),
    step('[data-open-lesson-editor]', 'Editar linhas da aula', 'O editor da aula organiza textos, slides, vídeos e considerações finais. Abra Como usar dentro dele para os detalhes.'),
    create('activity', 'Criar atividade', 'Informe instruções e prazo e vincule à aula quando aplicável. Revise o que será solicitado aos jovens.', 'academic.manage'),
    step('[data-toggle-course-status]', 'Publicar ou voltar a rascunho', 'A mudança afeta a disponibilidade do conteúdo. Confira aulas e atividades antes de publicar.', 'academic.manage'),
    step('[data-archive-course], [data-delete-course]', 'Arquivar e excluir', 'Arquivar preserva o curso fora do uso ativo. Excluir é uma ação diferente e exige atenção aos vínculos e ao histórico.', 'academic.manage')),
  'lesson-editor': guide('Editor da aula',
    intro('Organize a linha de aprendizagem', 'As linhas formam a sequência da aula que o jovem percorre. Dê uma ordem clara ao conteúdo.'),
    step('[data-edit-lesson]', 'Identificação da aula', 'Altere título e demais informações da aula sem precisar criar outra.', 'academic.manage'),
    create('block', 'Adicionar linha', 'Escolha texto, slides, vídeo ou considerações finais. Preencha o conteúdo do tipo selecionado.', 'academic.manage'),
    step('.block-admin-list', 'Confira as linhas', 'A lista mostra tipo, posição e resumo do conteúdo. Use Editar para revisar cada linha.'),
    step('[data-move-block]', 'Mudar a ordem', 'As setas sobem ou descem a linha na sequência. Excluir remove conteúdo e deve ser confirmado com cuidado.', 'academic.manage'),
    create('activity', 'Atividade da aula', 'Cadastre instruções e prazo. Ela complementa as linhas; o guia não cria nem responde atividades.', 'academic.manage')),
  enrollments: guide('Matrículas',
    intro('Vincule jovem e curso', 'Uma matrícula libera o curso para o jovem, conforme a disponibilidade do conteúdo.'),
    create('enrollment', 'Nova matrícula', 'Selecione jovem e curso existentes. O botão fica indisponível quando faltam cadastros necessários.', 'academic.manage'),
    step('.notice', 'Quando faltam opções', 'Cadastre o jovem e prepare o curso antes de matricular. Não crie contas duplicadas para contornar uma opção ausente.'),
    step('.list-table', 'Confira os vínculos', 'Leia jovem, curso e data da matrícula para evitar vínculos incorretos.'),
    step('[data-remove-enrollment]', 'Remover matrícula', 'A remoção afeta o acesso do jovem ao curso. Confira a pessoa e o conteúdo antes de confirmar.', 'academic.manage')),
  'student-home': guide('Início do jovem',
    intro('Sua formação', 'Este início reúne cursos liberados pela CAFCM e seu progresso.'),
    metrics('Os cartões mostram cursos, aulas e atividades registradas. O guia não marca aulas como concluídas.'),
    step('.student-course-list', 'Continue aprendendo', 'Abra um curso disponível para retomar suas aulas. Se não houver cursos, aguarde a matrícula da CAFCM.'),
    step('[data-nav="student-courses"]', 'Meus cursos', 'Veja a lista completa pelo menu. Cada página tem seu próprio guia no botão Como usar.')),
  'student-courses': guide('Meus cursos',
    intro('Cursos liberados', 'Aqui aparecem os cursos disponibilizados por meio da sua matrícula.'),
    step('.course-card', 'Escolha um curso', 'Confira título, categoria, descrição e carga horária antes de abrir.'),
    step('.progress-line', 'Seu progresso', 'A barra mostra aulas registradas como concluídas. Entrar no curso ou abrir o guia não equivale a concluí-lo.'),
    step('[data-open-course]', 'Abrir para estudar', 'Depois de abrir, veja aulas e atividades e use Como usar para aprender essa tela.')),
  'student-activities': guide('Atividades do jovem',
    intro('Acompanhe seus envios', 'Confira as atividades dos cursos liberados e os prazos definidos pela CAFCM.'),
    step('.activity-card', 'Leia a proposta', 'Cada cartão mostra instruções, vínculo e situação disponível. Confira antes de responder.'),
    step('.activity-foot', 'Prazo e situação', 'Observe o prazo e se a atividade já foi enviada. Solicite orientação à CAFCM em caso de dúvida.'),
    step('[data-answer-activity]', 'Responder atividade', 'O botão abre sua resposta. Leia as instruções e revise antes de enviar. O guia não responde nem envia por você.')),
  'student-course': guide('Curso do jovem',
    intro('Conteúdo e objetivos', 'Confira o que você aprenderá e a carga horária do curso.'),
    step('.progress-ring', 'Aulas concluídas', 'O percentual acompanha o progresso registrado. Atividades podem ter envios próprios além da conclusão da aula.'),
    step('[data-open-lesson]', 'Abra uma aula', 'Escolha a aula e percorra as linhas de aprendizagem. Dentro da aula há outro Como usar.'),
    step('[data-answer-activity]', 'Atividades do curso', 'Leia prazo e instruções. As respostas ficam protegidas; a empresa acompanha o status, não o conteúdo da resposta.')),
  'student-lesson': guide('Aula do jovem',
    step('.lesson-player-top', 'Você está na aula', 'Confira o título e a sequência. Voltar ao curso sai da aula sem concluir automaticamente.'),
    step('.lesson-player-progress', 'Etapas da aprendizagem', 'Acompanhe sua posição e avance pelas linhas na ordem proposta.'),
    step('.lesson-stage', 'Estude o conteúdo', 'A linha pode conter texto, imagem, slides, vídeo ou considerações finais. Leia e assista antes de avançar.'),
    step('.inner-slide-controls', 'Slides dentro da linha', 'Se houver slides, use os controles da apresentação. Eles são diferentes dos controles que mudam a etapa da aula.'),
    step('.lesson-player-actions', 'Voltar e avançar', 'Próximo leva à etapa seguinte; Voltar revisita a anterior. O guia tem seus próprios controles e não avança o estudo por você.'),
    step('[data-answer-activity]', 'Responder', 'Quando houver atividade, abra o formulário, leia a proposta e envie sua própria resposta.'),
    step('[data-complete-lesson]', 'Concluir aula', 'Conclua após terminar o conteúdo. Essa ação registra progresso real. Encerrar este tutorial não conclui a aula.')),
  'company-home': guide('Visão geral da empresa',
    intro('Acompanhamento da sua empresa', 'Esta visão inclui apenas jovens vinculados à sua empresa. Dados de outras empresas não são exibidos.'),
    metrics('Confira jovens vinculados, matrículas e atividades enviadas para orientar o acompanhamento.'),
    step('.company-list', 'Leia o progresso', 'Os resumos mostram avanços nos cursos. A empresa acompanha situação, não as respostas privadas das atividades.'),
    step('[data-nav="company-apprentices"]', 'Ver detalhes', 'Abra Aprendizes para ver cada jovem e curso. O guia dessa aba explica as situações de estudo.')),
  'company-apprentices': guide('Aprendizes da empresa',
    intro('Jovens vinculados', 'Consulte os jovens acompanhados pela sua empresa. Vínculos incorretos devem ser ajustados pela CAFCM.'),
    step('.company-person', 'Identifique o jovem', 'Confira nome e cursos atribuídos. Um jovem sem matrícula ainda não tem curso liberado neste acompanhamento.'),
    step('.company-progress', 'Percentual de aulas', 'A barra indica o percentual de aulas concluídas no curso, não uma nota ou ranking.'),
    step('.company-course-summary', 'Aulas e atividades', 'Compare aulas concluídas e atividades enviadas com os totais previstos. São medidas diferentes.'),
    step('.study-status', 'Situação de estudo', 'Ainda não iniciou, Em andamento e Concluído ajudam a orientar o jovem. Converse com ele e com a CAFCM quando precisar de acompanhamento.')),
};

const subviews = { finance: ['financeTab', 'receivable'], vacancies: ['vacancyTab', 'overview'], documents: ['documentTab', 'files'], automations: ['automationTab', 'overview'] };

export function guideKeyFor(state) {
  if (state.view === 'student-course' && state.selectedLessonId) return 'student-lesson';
  const subview = subviews[state.view];
  return subview ? `${state.view}:${state[subview[0]] || subview[1]}` : state.view;
}

export function getPageGuide(state, hasPermission = () => false) {
  const key = guideKeyFor(state);
  const result = pageGuides[key];
  if (!result) return null;
  return { ...result, key, steps: result.steps.filter(item => !item.permission || hasPermission(item.permission)) };
}
