import fs from 'fs';
let content = fs.readFileSync('src/app.js', 'utf8');

const recurringBodySearch = `  } else if (state.financeTab === "recurring") {
    body = \`<section class="card"><div class="people-list finance-list">\${recurring.length ? recurring.map((item) => { return \`<article class="person-row finance-row"><span class="avatar">\${icon("clock")}</span><div class="person-main"><strong>\${escapeHtml(companyMap.get(item.company_id) || "Empresa")}</strong><small>\${escapeHtml(item.description)} · Venc. \${item.due_day}</small></div><div class="finance-amount"><small>Regra</small><strong>\${item.value_rule === "fixed" ? formatMoney(item.fixed_amount) : item.value_rule === "per_apprentice" ? "Por Jovem" : "% Folha"}</strong></div><div class="person-access"><span class="status status-draft">\${item.is_active ? "Ativa" : "Inativa"}</span></div><div class="person-actions">\${canManage ? \`<button class="btn btn-small btn-secondary" data-edit-recurring="\${item.id}">\${icon("edit")} Alterar</button>\` : ""}</div></article>\`; }).join("") : emptyState("Nenhuma recorrência", "Crie regras de faturamento contínuo.", canManage ? \`<button class="btn btn-primary" data-dialog="recurring-charge">Nova regra</button>\` : "")}</div></section>\`;
  } else if (state.financeTab === "billets") {`;

const recurringBodyReplace = `  } else if (state.financeTab === "recurring") {
    body = \`
      \${canManage ? \`<section class="card"><div class="card-head"><div><span class="eyebrow">Ações em Lote</span><h2>Gerar Lançamentos</h2></div></div><div class="form-grid two-columns" style="padding: 1rem;"><label>Competência<input type="month" id="batch-competence" value="\${state.financeMonth}"/></label><button class="btn btn-secondary" data-preview-batch style="align-self: end; margin-bottom: 1rem;">Visualizar Prévia</button></div></section>\` : ""}
      <section class="card"><div class="card-head"><div><h2>Regras Ativas</h2></div></div><div class="people-list finance-list">\${recurring.length ? recurring.map((item) => { return \`<article class="person-row finance-row"><span class="avatar">\${icon("clock")}</span><div class="person-main"><strong>\${item.charge_type === "payable" ? escapeHtml(item.supplier_name) : escapeHtml(companyMap.get(item.company_id) || "Empresa")}</strong><small>\${escapeHtml(item.description)} · Venc. \${item.due_day} \${item.charge_type === "payable" ? "(Despesa)" : "(Faturamento)"}</small></div><div class="finance-amount"><small>Regra</small><strong>\${item.value_rule === "fixed" ? formatMoney(item.fixed_amount) : item.value_rule === "per_apprentice" ? "Por Jovem" : "% Folha"}</strong></div><div class="person-access"><span class="status status-draft">\${item.is_active ? "Ativa" : "Inativa"}</span></div><div class="person-actions">\${canManage ? \`<button class="btn btn-small btn-secondary" data-edit-recurring="\${item.id}">\${icon("edit")} Alterar</button>\` : ""}</div></article>\`; }).join("") : emptyState("Nenhuma recorrência", "Crie regras de faturamento contínuo.", canManage ? \`<button class="btn btn-primary" data-dialog="recurring-charge">Nova regra</button>\` : "")}</div></section>\`;
  } else if (state.financeTab === "billets") {`;

content = content.replace(recurringBodySearch, recurringBodyReplace);
fs.writeFileSync('src/app.js', content);
